In [1]:
import pandas as pd
import numpy as np

In [2]:
pip install ipykernel

Requirement already satisfied: ipykernel in d:\sath\End to End DL project\venv\Lib\site-packages (7.3.0)
Requirement already satisfied: comm>=0.1.1 in d:\sath\End to End DL project\venv\Lib\site-packages (from ipykernel) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in d:\sath\End to End DL project\venv\Lib\site-packages (from ipykernel) (1.8.21)
Requirement already satisfied: ipython>=7.23.1 in d:\sath\End to End DL project\venv\Lib\site-packages (from ipykernel) (9.14.1)
Requirement already satisfied: jupyter-client>=8.9.0 in d:\sath\End to End DL project\venv\Lib\site-packages (from ipykernel) (8.9.1)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in d:\sath\End to End DL project\venv\Lib\site-packages (from ipykernel) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in d:\sath\End to End DL project\venv\Lib\site-packages (from ipykernel) (0.2.2)
Requirement already satisfied: nest-asyncio2>=1.7.0 in d:\sath\End to End DL project\venv\Lib\site-packages (from ipykernel) (1.7.2)
Requirement already satisfied: packaging>=22 in d:\sath\End to End DL project\venv\Lib\site-packages (from ipykernel) (26.0)
Requirement already satisfied: psutil>=5.7 in d:\sath\End to End DL project\venv\Lib\site-packages (from ipykernel) (7.2.2)
Requirement already satisfied: pyzmq>=25 in d:\sath\End to End DL project\venv\Lib\site-packages (from ipykernel) (27.1.0)
Requirement already satisfied: tornado>=6.4.1 in d:\sath\End to End DL project\venv\Lib\site-packages (from ipykernel) (6.5.7)
Requirement already satisfied: traitlets>=5.4.0 in d:\sath\End to End DL project\venv\Lib\site-packages (from ipykernel) (5.15.1)
Requirement already satisfied: colorama>=0.4.4 in d:\sath\End to End DL project\venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in d:\sath\End to End DL project\venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (5.3.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in d:\sath\End to End DL project\venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in d:\sath\End to End DL project\venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (0.20.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in d:\sath\End to End DL project\venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in d:\sath\End to End DL project\venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in d:\sath\End to End DL project\venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)
Requirement already satisfied: typing_extensions>=4.6 in d:\sath\End to End DL project\venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (4.15.0)
Requirement already satisfied: wcwidth in d:\sath\End to End DL project\venv\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.8.1)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in d:\sath\End to End DL project\venv\Lib\site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel) (0.8.7)
Requirement already satisfied: python-dateutil>=2.8.2 in d:\sath\End to End DL project\venv\Lib\site-packages (from jupyter-client>=8.9.0->ipykernel) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in d:\sath\End to End DL project\venv\Lib\site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel) (4.10.0)
Requirement already satisfied: six>=1.5 in d:\sath\End to End DL project\venv\Lib\site-packages (from python-dateutil>=2.8.2->jupyter-client>=8.9.0->ipykernel) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in d:\sath\End to End DL project\venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in d:\sath\End to End DL project\venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (3.0.1)
Requirement already satisfied: pure-eval in d:\sath\End to End DL project\venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (0.2.3)
Note: you may need to restart the kernel to use updated packages.

In [3]:
df=pd.read_csv('Churn_Modelling (1).csv')

In [4]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [16]:
df=df.drop(['RowNumber','CustomerId','Surname'],axis=1)

In [17]:
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [6]:
from sklearn.preprocessing import LabelEncoder
label_enccoder=LabelEncoder()
df['Gender']=label_enccoder.fit_transform(df['Gender'])

In [7]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [8]:
from sklearn.preprocessing import OneHotEncoder
one_encoded=OneHotEncoder()
geo_encoded=one_encoded.fit_transform(df[['Geography']])

In [9]:
geo_encoded

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [10]:
one_encoded.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [12]:
geo_encoded_df=pd.DataFrame(geo_encoded.toarray(),columns=one_encoded.get_feature_names_out(['Geography']))

In [13]:
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [14]:
df=pd.concat([df.drop(['Geography'],axis=1),geo_encoded_df],axis=1)

In [18]:
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [19]:
import pickle

In [21]:
with open('label_encoded.pkl','wb') as file:
    pickle.dump(label_enccoder,file)
with open('Hot_encoded.pkl','wb') as file:
    pickle.dump(one_encoded,file)

In [23]:
x=df.drop(['Exited'],axis=1)
y=df['Exited']

In [25]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [26]:
x_train.shape

(8000, 12)

In [27]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [28]:
x_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [29]:
x_test

array([[-0.57749609,  0.91324755, -0.6557859 , ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.29729735,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.52560743, -1.09499335,  0.48508334, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.81311987, -1.09499335,  0.77030065, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.41876609,  0.91324755, -0.94100321, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.24540869,  0.91324755,  0.00972116, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [30]:
with open('scaler.pkl','wb') as file:
    pickle.dump(scaler,file)

In [33]:
%pip install tensorflow
## create a model
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

Requirement already satisfied: tensorflow in d:\sath\End to End DL project\venv\Lib\site-packages (2.16.1)
Requirement already satisfied: tensorflow-intel==2.16.1 in d:\sath\End to End DL project\venv\Lib\site-packages (from tensorflow) (2.16.1)
Requirement already satisfied: absl-py>=1.0.0 in d:\sath\End to End DL project\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in d:\sath\End to End DL project\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in d:\sath\End to End DL project\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in d:\sath\End to End DL project\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in d:\sath\End to End DL project\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (0.2.0)
Requirement already satisfied: h5py>=3.10.0 in d:\sath\End to End DL project\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (3.16.0)
Requirement already satisfied: libclang>=13.0.0 in d:\sath\End to End DL project\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (18.1.1)
Requirement already satisfied: ml-dtypes~=0.3.1 in d:\sath\End to End DL project\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (0.3.2)
Requirement already satisfied: opt-einsum>=2.3.2 in d:\sath\End to End DL project\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (3.4.0)
Requirement already satisfied: packaging in d:\sath\End to End DL project\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (26.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in d:\sath\End to End DL project\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (4.25.9)
Requirement already satisfied: requests<3,>=2.21.0 in d:\sath\End to End DL project\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (2.34.2)
Requirement already satisfied: setuptools in d:\sath\End to End DL project\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (80.10.2)
Requirement already satisfied: six>=1.12.0 in d:\sath\End to End DL project\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in d:\sath\End to End DL project\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in d:\sath\End to End DL project\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in d:\sath\End to End DL project\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (2.2.1)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in d:\sath\End to End DL project\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (1.81.0)
Requirement already satisfied: tensorboard<2.17,>=2.16 in d:\sath\End to End DL project\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (2.16.2)
Requirement already satisfied: keras>=3.0.0 in d:\sath\End to End DL project\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (3.14.1)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in d:\sath\End to End DL project\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (0.31.0)
Requirement already satisfied: numpy<2.0.0,>=1.23.5 in d:\sath\End to End DL project\venv\Lib\site-packages (from tensorflow-intel==2.16.1->tensorflow) (1.26.4)
Requirement already satisfied: charset_normalizer<4,>=2 in d:\sath\End to End DL project\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.16.1->tensorflow) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in d:\sath\End to End DL project\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.16.1->tensorflow) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in d:\sath\End to End DL project\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.16.1->tensorflow) (2.7.0)
Requirement already satisfied: certifi>=2023.5.7 in d:\sath\End to End DL project\venv\Lib\site-packages (from requests<3,>=2.21.0->tensorflow-intel==2.16.1->tensorflow) (2026.5.20)
Requirement already satisfied: markdown>=2.6.8 in d:\sath\End to End DL project\venv\Lib\site-packages (from tensorboard<2.17,>=2.16->tensorflow-intel==2.16.1->tensorflow) (3.10.2)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in d:\sath\End to End DL project\venv\Lib\site-packages (from tensorboard<2.17,>=2.16->tensorflow-intel==2.16.1->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in d:\sath\End to End DL project\venv\Lib\site-packages (from tensorboard<2.17,>=2.16->tensorflow-intel==2.16.1->tensorflow) (3.1.8)
Requirement already satisfied: wheel<1.0,>=0.23.0 in d:\sath\End to End DL project\venv\Lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.16.1->tensorflow) (0.46.3)
Requirement already satisfied: rich in d:\sath\End to End DL project\venv\Lib\site-packages (from keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow) (15.0.0)
Requirement already satisfied: namex in d:\sath\End to End DL project\venv\Lib\site-packages (from keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow) (0.1.0)
Requirement already satisfied: optree in d:\sath\End to End DL project\venv\Lib\site-packages (from keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow) (0.19.1)
Requirement already satisfied: markupsafe>=2.1.1 in d:\sath\End to End DL project\venv\Lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.17,>=2.16->tensorflow-intel==2.16.1->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in d:\sath\End to End DL project\venv\Lib\site-packages (from rich->keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in d:\sath\End to End DL project\venv\Lib\site-packages (from rich->keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in d:\sath\End to End DL project\venv\Lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.0.0->tensorflow-intel==2.16.1->tensorflow) (0.1.2)
Note: you may need to restart the kernel to use updated packages.

In [34]:
x_train.shape[1]

12

In [38]:
model=Sequential([
    Dense(64,activation='relu',input_shape=(x_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(1,activation='sigmoid')
])

In [39]:
model.summary()

Model: "sequential_3"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [56]:
##compile 
model.compile(optimizer='Adam',loss='binary_crossentropy',metrics=['accuracy'])

In [61]:
model.save("model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [62]:
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

In [51]:
tensorboard_callback = TensorBoard(
    log_dir=log_dir,
    histogram_freq=1
)

In [52]:
tensorboard_callback

In [53]:
early_stopping_callback=EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

In [54]:
early_stopping_callback

In [58]:
##train the model with tensorboard
training=model.fit(
    x_train,
    y_train,
    epochs=100,
    validation_data=(x_test,y_test),
    callbacks=[tensorboard_callback,early_stopping_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 7ms/step - accuracy: 0.7690 - loss: 0.4898 - val_accuracy: 0.8325 - val_loss: 0.3963
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8405 - loss: 0.3907 - val_accuracy: 0.8515 - val_loss: 0.3620
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.8540 - loss: 0.3588 - val_accuracy: 0.8575 - val_loss: 0.3488
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.8583 - loss: 0.3476 - val_accuracy: 0.8620 - val_loss: 0.3447
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8591 - loss: 0.3414 - val_accuracy: 0.8595 - val_loss: 0.3436
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8590 - loss: 0.3382 - val_accuracy: 0.8615 - val_loss: 0.3409
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8602 - loss: 0.3363 - val_accuracy: 0.8550 - val_loss: 0.3430
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8644 - loss: 0.3325 - val_accuracy: 0.8650 - val_loss: 0.3434
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8624 - loss: 0.3295 - val_accuracy: 0.8630 - val_loss: 0.3423
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8640 - loss: 0.3275 - val_accuracy: 0.8600 - val_loss: 0.3475
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8634 - loss: 0.3261 - val_accuracy: 0.8610 - val_loss: 0.3373
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8627 - loss: 0.3239 - val_accuracy: 0.8600 - val_loss: 0.3428
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8649 - loss: 0.3234 - val_accuracy: 0.8630 - val_loss: 0.3416
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8659 - loss: 0.3215 - val_accuracy: 0.8595 - val_loss: 0.3484
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - accuracy: 0.8670 - loss: 0.3181 - val_accuracy: 0.8555 - val_loss: 0.3435
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - accuracy: 0.8692 - loss: 0.3178 - val_accuracy: 0.8620 - val_loss: 0.3390

In [60]:
%load_ext tensorboard
%tensorboard --logdir logs/fit

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

Reusing TensorBoard on port 6006 (pid 9816), started 0:00:04 ago. (Use '!kill 9816' to kill it.)

In [64]:
##predictionn
from tensorflow.keras.models import load_model
import pandas as pd
import numpy as np

In [65]:
model=load_model('model.h5')

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [66]:
model

In [67]:
with open('label_encoded.pkl','rb') as file:
    label_encoded=pickle.load(file)
with open('Hot_encoded.pkl','rb') as file:
    Hot_encoded=pickle.load(file)
with open('scaler.pkl','rb') as file:
    scaler=pickle.load(file)

In [68]:
df.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [73]:
input_data={
    'CreditScore':670,
    'Gender':'Female',
    'Geography':'France',
    'Age':66,
    'Tenure':4,
    'Balance':67000,
    'NumOfProducts':2,
    'HasCrCard':1,
    'IsActiveMember':1,
    'EstimatedSalary':90000,
    
}

In [74]:
data=pd.DataFrame([input_data])

In [75]:
data

,CreditScore,Gender,Geography,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,670,Female,France,66,4,67000,2,1,1,90000

In [81]:
data['Gender']=label_encoded.transform(data['Gender'])

In [82]:
data

,CreditScore,Gender,Geography,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,670,0,France,66,4,67000,2,1,1,90000

In [84]:
one_encoded_geo=Hot_encoded.transform(data[['Geography']])

In [85]:
one_encoded_geo

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 1 stored elements and shape (1, 3)>

In [90]:
features=Hot_encoded.get_feature_names_out(['Geography'])

In [91]:
features

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [93]:
one_encoded_geo_df=pd.DataFrame(one_encoded_geo.toarray(),columns=features)

In [94]:
one_encoded_geo_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [95]:
data=pd.concat([data.drop(['Geography'],axis=1),one_encoded_geo_df],axis=1)

In [96]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,670,0,66,4,67000,2,1,1,90000,1.0,0.0,0.0

In [97]:
##scaling the data
data_scaled=scaler.transform(data)

In [98]:
data_scaled

array([[ 0.19045601, -1.09499335,  2.57667694, -0.3483691 , -0.14573426,
         0.80843615,  0.64920267,  0.97481699, -0.1813654 ,  1.00150113,
        -0.57946723, -0.57638802]])

In [100]:
## predict
prediction=model.predict(data_scaled)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step

In [101]:
prediction_pron=prediction[0][0]

In [102]:
prediction_pron

0.08744136

In [103]:
if prediction_pron>0.5:
    print("the customer is likely to churn")
    
else:
    print("the customer is not likely to churn")

the customer is not likely to churn